substitutions:
  _REGION: "us-central1"
  _REPOSITORY: "jwt-api-repo"
  _IMAGE: "jwt-auth-api"
  _SERVICE: "jwt-auth-service"

steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['-B', 'clean', 'test']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', '$_SERVICE',
        '--image', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA',
        '--region', '$_REGION',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--memory', '512Mi',
        '--cpu', '1'
      ]
options:
    logging: CLOUD_LOGGING_ONLY

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA'
